# Generated by Django 3.2.12 on 2022-03-18 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.forms.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictateur_name', models.CharField(max_length=50)),
                ('dictateur_maison', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paysan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paysan_name', models.CharField(max_length=50)),
                ('paysan_role', models.IntegerField(choices=[(1, 'Electeur'), (2, 'Admin')])),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_name', models.CharField(max_length=50)),
                ('regime_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=50)),
                ('election_date', models.DateTimeField(verbose_name='Date des élections')),
                ('election_nbr_tour', models.IntegerField(verbose_name=django.forms.widgets.NumberInput)),
                ('election_dictateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.dictateur')),
                ('election_paysan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.paysan')),
            ],
        ),
        migrations.AddField(
            model_name='dictateur',
            name='dictateur_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.regime'),
        ),
    ]
