# Generated by Django 3.2.12 on 2022-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20220318_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictateur',
            name='dictateur_votes',
            field=models.IntegerField(default=0),
        ),
    ]
