# Generated by Django 3.2.12 on 2022-03-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_dictateur_dictateur_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictateur',
            old_name='dictateur_votes',
            new_name='votes',
        ),
        migrations.DeleteModel(
            name='Paysan',
        ),
    ]
