# Generated by Django 3.2.12 on 2022-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_dictateur_dictateur_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictateur',
            name='dictateur_blason',
            field=models.ImageField(blank=True, upload_to='blason'),
        ),
    ]
